In [104]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [105]:
df=pd.read_csv("stock_data.csv")
df

,Date,RELIANCE,TCS,HDFCBANK,ICICIBANK,BHARTIARTL,SBIN,INFY,LICI,ITC,...,COOLCAPS,ALLETEC,20MICRONS,VIKASECO,ORIENTBELL,DONEAR,CAREERP,INTLCONV,SHREEPUSHK,PRITIKAUTO
0,1991-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1991-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1991-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1991-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1991-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8465,2024-07-01,3120.300049,3978.199951,1705.199951,1211.849976,1454.000000,841.950012,1590.800049,996.349976,429.049988,...,NaN,NaN,220.410004,3.90,402.799988,134.960007,384.850006,82.779999,211.089996,27.440001
8466,2024-07-02,3130.350098,4017.399902,1730.599976,1190.599976,1418.949951,826.150024,1621.050049,985.450012,425.500000,...,NaN,NaN,216.110001,3.87,409.799988,130.729996,396.700012,83.349998,211.740005,27.770000
8467,2024-07-03,3104.850098,3965.250000,1768.650024,1201.599976,1419.849976,839.950012,1627.400024,988.200012,428.299988,...,NaN,NaN,227.800003,3.87,429.350006,132.220001,394.200012,83.269997,225.880005,27.700001
8468,2024-07-04,3108.050049,4020.949951,1727.150024,1233.000000,1423.050049,839.299988,1650.650024,1010.200012,429.049988,...,NaN,NaN,227.429993,4.04,428.750000,131.360001,388.250000,82.980003,223.800003,27.580000
8469,2024-07-05,3177.250000,4011.800049,1648.099976,1233.400024,1429.699951,859.750000,1647.449951,1015.650024,433.649994,...,NaN,NaN,224.720001,3.98,421.350006,130.440002,388.799988,84.099998,241.740005,27.910000

In [106]:
df1=df["Date"]
df1

0       1991-01-02
1       1991-01-03
2       1991-01-04
3       1991-01-07
4       1991-01-08
           ...
8465    2024-07-01
8466    2024-07-02
8467    2024-07-03
8468    2024-07-04
8469    2024-07-05
Name: Date, Length: 8470, dtype: object

In [107]:
df['Date'] = pd.to_datetime(df['Date'])
filtered_df = df[(df['Date'] >= '2020-01-01') & (df['Date'] <= '2024-07-05')]

In [108]:
filtered_df

,Date,RELIANCE,TCS,HDFCBANK,ICICIBANK,BHARTIARTL,SBIN,INFY,LICI,ITC,...,COOLCAPS,ALLETEC,20MICRONS,VIKASECO,ORIENTBELL,DONEAR,CAREERP,INTLCONV,SHREEPUSHK,PRITIKAUTO
7353,2020-01-01,1380.276611,2167.600098,1278.599976,536.750000,444.946136,334.450012,736.849976,NaN,238.100006,...,NaN,NaN,35.799999,1.905344,130.750000,30.100000,108.300003,NaN,104.150002,NaN
7354,2020-01-02,1403.775024,2157.649902,1286.750000,540.599976,446.811127,339.299988,734.700012,NaN,239.850006,...,NaN,NaN,35.549999,1.874109,133.100006,32.200001,111.800003,NaN,107.500000,NaN
7355,2020-01-03,1405.466553,2200.649902,1268.400024,538.849976,446.712952,333.700012,746.000000,NaN,238.500000,...,NaN,NaN,35.049999,1.811639,135.750000,30.950001,113.500000,NaN,104.300003,NaN
7356,2020-01-06,1372.870605,2200.449951,1240.949951,525.700012,441.363403,319.000000,738.849976,NaN,235.100006,...,NaN,NaN,32.799999,1.811639,128.750000,29.900000,108.300003,NaN,100.050003,NaN
7357,2020-01-07,1393.991699,2205.850098,1260.599976,522.900024,436.897247,318.399994,727.900024,NaN,235.350006,...,NaN,NaN,33.200001,1.842874,136.000000,30.049999,112.550003,NaN,105.599998,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8465,2024-07-01,3120.300049,3978.199951,1705.199951,1211.849976,1454.000000,841.950012,1590.800049,996.349976,429.049988,...,NaN,NaN,220.410004,3.900000,402.799988,134.960007,384.850006,82.779999,211.089996,27.440001
8466,2024-07-02,3130.350098,4017.399902,1730.599976,1190.599976,1418.949951,826.150024,1621.050049,985.450012,425.500000,...,NaN,NaN,216.110001,3.870000,409.799988,130.729996,396.700012,83.349998,211.740005,27.770000
8467,2024-07-03,3104.850098,3965.250000,1768.650024,1201.599976,1419.849976,839.950012,1627.400024,988.200012,428.299988,...,NaN,NaN,227.800003,3.870000,429.350006,132.220001,394.200012,83.269997,225.880005,27.700001
8468,2024-07-04,3108.050049,4020.949951,1727.150024,1233.000000,1423.050049,839.299988,1650.650024,1010.200012,429.049988,...,NaN,NaN,227.429993,4.040000,428.750000,131.360001,388.250000,82.980003,223.800003,27.580000
8469,2024-07-05,3177.250000,4011.800049,1648.099976,1233.400024,1429.699951,859.750000,1647.449951,1015.650024,433.649994,...,NaN,NaN,224.720001,3.980000,421.350006,130.440002,388.799988,84.099998,241.740005,27.910000

In [140]:
transposed_df = filtered_df.transpose()

In [ ]:
={"email_message":x,"label":y}
email_data=pd.DataFrame(dt)
email_data.head()

In [138]:
transposed_df.reset_index(drop=True,inplace=True)

In [141]:
transposed_df

,7353,7354,7355,7356,7357,7358,7359,7360,7361,7362,...,8460,8461,8462,8463,8464,8465,8466,8467,8468,8469
Date,2020-01-01 00:00:00,2020-01-02 00:00:00,2020-01-03 00:00:00,2020-01-06 00:00:00,2020-01-07 00:00:00,2020-01-08 00:00:00,2020-01-09 00:00:00,2020-01-10 00:00:00,2020-01-13 00:00:00,2020-01-14 00:00:00,...,2024-06-24 00:00:00,2024-06-25 00:00:00,2024-06-26 00:00:00,2024-06-27 00:00:00,2024-06-28 00:00:00,2024-07-01 00:00:00,2024-07-02 00:00:00,2024-07-03 00:00:00,2024-07-04 00:00:00,2024-07-05 00:00:00
RELIANCE,1380.276611,1403.775024,1405.466553,1372.870605,1393.991699,1383.522583,1415.387085,1415.067017,1411.455444,1398.380493,...,2882.949951,2908.300049,3028.050049,3061.100098,3130.800049,3120.300049,3130.350098,3104.850098,3108.050049,3177.25
TCS,2167.600098,2157.649902,2200.649902,2200.449951,2205.850098,2255.25,2214.350098,2213.550049,2190.350098,2206.899902,...,3816.800049,3838.449951,3855.850098,3934.149902,3904.149902,3978.199951,4017.399902,3965.25,4020.949951,4011.800049
HDFCBANK,1278.599976,1286.75,1268.400024,1240.949951,1260.599976,1257.300049,1271.400024,1282.699951,1286.0,1289.5,...,1672.400024,1711.349976,1701.5,1696.150024,1683.800049,1705.199951,1730.599976,1768.650024,1727.150024,1648.099976
ICICIBANK,536.75,540.599976,538.849976,525.700012,522.900024,525.950012,546.299988,540.25,538.599976,537.599976,...,1170.099976,1197.949951,1218.0,1219.900024,1199.599976,1211.849976,1190.599976,1201.599976,1233.0,1233.400024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VIKASECO,1.905344,1.874109,1.811639,1.811639,1.842874,1.811639,1.842874,1.811639,1.749168,1.749168,...,3.95,3.92,3.95,3.88,3.85,3.9,3.87,3.87,4.04,3.98
ORIENTBELL,130.75,133.100006,135.75,128.75,136.0,135.600006,142.600006,140.5,134.699997,134.699997,...,406.350006,402.350006,404.600006,402.399994,392.549988,402.799988,409.799988,429.350006,428.75,421.350006
DONEAR,30.1,32.200001,30.950001,29.9,30.049999,29.700001,30.85,31.200001,30.75,30.950001,...,136.699997,135.270004,140.080002,133.910004,135.740005,134.960007,130.729996,132.220001,131.360001,130.440002
CAREERP,108.300003,111.800003,113.5,108.300003,112.550003,114.800003,118.400002,117.900002,118.900002,119.050003,...,398.25,403.299988,400.299988,396.25,390.649994,384.850006,396.700012,394.200012,388.25,388.799988
SHREEPUSHK,104.150002,107.5,104.300003,100.050003,105.599998,105.550003,118.699997,114.400002,116.449997,117.650002,...,215.080002,206.869995,202.740005,199.080002,210.550003,211.089996,211.740005,225.880005,223.800003,241.740005

In [109]:
filtered_df.dropna(axis=1,inplace=True)

C:\Users\Pragati\AppData\Local\Temp\ipykernel_13684\3625111044.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df.dropna(axis=1,inplace=True)

In [110]:
filtered_df.isnull().sum()

Date          0
RELIANCE      0
TCS           0
HDFCBANK      0
ICICIBANK     0
             ..
VIKASECO      0
ORIENTBELL    0
DONEAR        0
CAREERP       0
SHREEPUSHK    0
Length: 1055, dtype: int64

In [111]:
filtered_df

,Date,RELIANCE,TCS,HDFCBANK,ICICIBANK,BHARTIARTL,SBIN,INFY,ITC,HINDUNILVR,...,PTL,MOLDTECH,MAZDA,MINDTECK,20MICRONS,VIKASECO,ORIENTBELL,DONEAR,CAREERP,SHREEPUSHK
7353,2020-01-01,1380.276611,2167.600098,1278.599976,536.750000,444.946136,334.450012,736.849976,238.100006,1936.550049,...,18.200001,48.500000,399.899994,26.549999,35.799999,1.905344,130.750000,30.100000,108.300003,104.150002
7354,2020-01-02,1403.775024,2157.649902,1286.750000,540.599976,446.811127,339.299988,734.700012,239.850006,1938.050049,...,18.525000,48.900002,438.500000,26.350000,35.549999,1.874109,133.100006,32.200001,111.800003,107.500000
7355,2020-01-03,1405.466553,2200.649902,1268.400024,538.849976,446.712952,333.700012,746.000000,238.500000,1927.449951,...,18.750000,48.950001,432.899994,26.799999,35.049999,1.811639,135.750000,30.950001,113.500000,104.300003
7356,2020-01-06,1372.870605,2200.449951,1240.949951,525.700012,441.363403,319.000000,738.849976,235.100006,1915.449951,...,18.525000,49.349998,424.149994,25.600000,32.799999,1.811639,128.750000,29.900000,108.300003,100.050003
7357,2020-01-07,1393.991699,2205.850098,1260.599976,522.900024,436.897247,318.399994,727.900024,235.350006,1920.699951,...,18.375000,49.849998,419.950012,29.299999,33.200001,1.842874,136.000000,30.049999,112.550003,105.599998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8465,2024-07-01,3120.300049,3978.199951,1705.199951,1211.849976,1454.000000,841.950012,1590.800049,429.049988,2505.100098,...,46.189999,258.750000,1434.300049,313.850006,220.410004,3.900000,402.799988,134.960007,384.850006,211.089996
8466,2024-07-02,3130.350098,4017.399902,1730.599976,1190.599976,1418.949951,826.150024,1621.050049,425.500000,2485.149902,...,46.240002,261.500000,1449.849976,305.649994,216.110001,3.870000,409.799988,130.729996,396.700012,211.740005
8467,2024-07-03,3104.850098,3965.250000,1768.650024,1201.599976,1419.849976,839.950012,1627.400024,428.299988,2510.350098,...,46.270000,260.299988,1432.449951,325.399994,227.800003,3.870000,429.350006,132.220001,394.200012,225.880005
8468,2024-07-04,3108.050049,4020.949951,1727.150024,1233.000000,1423.050049,839.299988,1650.650024,429.049988,2495.949951,...,46.119999,258.000000,1422.050049,338.950012,227.429993,4.040000,428.750000,131.360001,388.250000,223.800003
8469,2024-07-05,3177.250000,4011.800049,1648.099976,1233.400024,1429.699951,859.750000,1647.449951,433.649994,2547.000000,...,47.119999,265.200012,1420.750000,328.350006,224.720001,3.980000,421.350006,130.440002,388.799988,241.740005

In [114]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Step 1: Filter the data and calculate rolling average

In [115]:
filtered_df['Date'] = pd.to_datetime(filtered_df['Date'])
filtered_df = filtered_df[(filtered_df['Date'] >= '2020-01-01')]
rolling_avg = filtered_df.drop('Date', axis=1).rolling(window=10).mean()

C:\Users\Pragati\AppData\Local\Temp\ipykernel_13684\2039335117.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['Date'] = pd.to_datetime(filtered_df['Date'])

In [131]:
# Step 2: Feature Engineering
features = pd.concat([filtered_df.drop('Date', axis=1), rolling_avg.shift(1)], axis=1)
labels = ((filtered_df.drop('Date', axis=1) > filtered_df.drop('Date', axis=1).shift(1)) & 
          (filtered_df.drop('Date', axis=1) > rolling_avg.shift(1)))

In [132]:
features

,RELIANCE,TCS,HDFCBANK,ICICIBANK,BHARTIARTL,SBIN,INFY,ITC,HINDUNILVR,LT,...,PTL,MOLDTECH,MAZDA,MINDTECK,20MICRONS,VIKASECO,ORIENTBELL,DONEAR,CAREERP,SHREEPUSHK
7353,1380.276611,2167.600098,1278.599976,536.750000,444.946136,334.450012,736.849976,238.100006,1936.550049,1309.949951,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7354,1403.775024,2157.649902,1286.750000,540.599976,446.811127,339.299988,734.700012,239.850006,1938.050049,1345.300049,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7355,1405.466553,2200.649902,1268.400024,538.849976,446.712952,333.700012,746.000000,238.500000,1927.449951,1335.050049,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7356,1372.870605,2200.449951,1240.949951,525.700012,441.363403,319.000000,738.849976,235.100006,1915.449951,1316.750000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7357,1393.991699,2205.850098,1260.599976,522.900024,436.897247,318.399994,727.900024,235.350006,1920.699951,1320.500000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8465,3120.300049,3978.199951,1705.199951,1211.849976,1454.000000,841.950012,1590.800049,429.049988,2505.100098,3526.550049,...,44.201,261.822002,1393.360010,301.094998,206.433998,3.873,386.499997,134.167000,392.639999,210.678003
8466,3130.350098,4017.399902,1730.599976,1190.599976,1418.949951,826.150024,1621.050049,425.500000,2485.149902,3626.500000,...,44.587,261.099001,1397.070020,302.800000,209.520999,3.886,390.914996,134.709001,395.270001,211.307002
8467,3104.850098,3965.250000,1768.650024,1201.599976,1419.849976,839.950012,1627.400024,428.299988,2510.350098,3614.350098,...,44.768,261.105000,1399.425012,304.035001,212.103000,3.900,394.569995,134.617001,397.245001,211.526003
8468,3108.050049,4020.949951,1727.150024,1233.000000,1423.050049,839.299988,1650.650024,429.049988,2495.949951,3573.300049,...,44.930,261.684000,1401.390002,306.650000,216.346001,3.919,400.004996,134.860002,397.595001,212.992003
8469,3177.250000,4011.800049,1648.099976,1233.400024,1429.699951,859.750000,1647.449951,433.649994,2547.000000,3627.149902,...,45.091,261.169998,1402.625012,310.745001,220.309000,3.930,405.149997,135.004002,395.510001,213.015002

In [134]:
for i in range(len(filtered_data)):
    filtered_data[""][i]=r

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [117]:
# Step 3: Model Training
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2, random_state=42)
model = RandomForestClassifier()
model.fit(X_train, y_train)

KeyboardInterrupt:

In [ ]:
# Step 4: Model Prediction
predictions = model.predict(X_test)

In [ ]:
# Step 5: Output
predicted_data = filtered_df.loc[y_test.index]
predicted_data['Predicted'] = predictions
print(predicted_data)

In [113]:
X = filtered_df['Date']
y = filtered_df.drop(['Date'], axis=1)
rolling_avg = y.rolling(window=10).mean()
previous_day=filtered_df.shift(1)
above_previous_day = y > previous_day
above_10_day_avg = y > rolling_avg
selected_data = df[(above_previous_day & above_10_day_avg).all(axis=1)]
print(selected_data)

ValueError: Can only compare identically-labeled (both index and columns) DataFrame objects

In [ ]:
from datetime import datetime, timedelta

In [ ]:
x = filtered_df['Date']
y = filtered_df.drop('Date', axis=1)

In [ ]:
x.shape

(1117,)

In [ ]:
y.shape

(1117, 1054)

In [ ]:
df['last_10_days_avg'] = df['y'].rolling(window=10).mean()
filtered_data = df[(df['last_10_days_avg'] > df['today_price']) & (df['last_10_days_avg'] > df['previous_day_price'])]

KeyError: 'y'

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])
user_input = input("Enter today's date (YYYY-MM-DD): ")
today = datetime.strptime(user_input, '%Y-%m-%d')
previous_date = today - timedelta(days=1)
start_date = today - timedelta(days=10)
filtered_df = df[(df['Date'] >= previous_date) & (df['Date'] <= today)]
last_10_days_df = df[(df['Date'] > start_date) & (df['Date'] <= today)]
average_prices = last_10_days_df.groupby('y')['price'].mean()
print(average_prices)

KeyError: 'y'

In [ ]:
filtered_df

,Date,RELIANCE,TCS,HDFCBANK,ICICIBANK,BHARTIARTL,SBIN,INFY,LICI,ITC,...,COOLCAPS,ALLETEC,20MICRONS,VIKASECO,ORIENTBELL,DONEAR,CAREERP,INTLCONV,SHREEPUSHK,PRITIKAUTO
7353,2020-01-01,1380.276611,2167.600098,1278.599976,536.750000,444.946136,334.450012,736.849976,NaN,238.100006,...,NaN,NaN,35.799999,1.905344,130.750000,30.100000,108.300003,NaN,104.150002,NaN
7354,2020-01-02,1403.775024,2157.649902,1286.750000,540.599976,446.811127,339.299988,734.700012,NaN,239.850006,...,NaN,NaN,35.549999,1.874109,133.100006,32.200001,111.800003,NaN,107.500000,NaN
7355,2020-01-03,1405.466553,2200.649902,1268.400024,538.849976,446.712952,333.700012,746.000000,NaN,238.500000,...,NaN,NaN,35.049999,1.811639,135.750000,30.950001,113.500000,NaN,104.300003,NaN
7356,2020-01-06,1372.870605,2200.449951,1240.949951,525.700012,441.363403,319.000000,738.849976,NaN,235.100006,...,NaN,NaN,32.799999,1.811639,128.750000,29.900000,108.300003,NaN,100.050003,NaN
7357,2020-01-07,1393.991699,2205.850098,1260.599976,522.900024,436.897247,318.399994,727.900024,NaN,235.350006,...,NaN,NaN,33.200001,1.842874,136.000000,30.049999,112.550003,NaN,105.599998,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8465,2024-07-01,3120.300049,3978.199951,1705.199951,1211.849976,1454.000000,841.950012,1590.800049,996.349976,429.049988,...,NaN,NaN,220.410004,3.900000,402.799988,134.960007,384.850006,82.779999,211.089996,27.440001
8466,2024-07-02,3130.350098,4017.399902,1730.599976,1190.599976,1418.949951,826.150024,1621.050049,985.450012,425.500000,...,NaN,NaN,216.110001,3.870000,409.799988,130.729996,396.700012,83.349998,211.740005,27.770000
8467,2024-07-03,3104.850098,3965.250000,1768.650024,1201.599976,1419.849976,839.950012,1627.400024,988.200012,428.299988,...,NaN,NaN,227.800003,3.870000,429.350006,132.220001,394.200012,83.269997,225.880005,27.700001
8468,2024-07-04,3108.050049,4020.949951,1727.150024,1233.000000,1423.050049,839.299988,1650.650024,1010.200012,429.049988,...,NaN,NaN,227.429993,4.040000,428.750000,131.360001,388.250000,82.980003,223.800003,27.580000
8469,2024-07-05,3177.250000,4011.800049,1648.099976,1233.400024,1429.699951,859.750000,1647.449951,1015.650024,433.649994,...,NaN,NaN,224.720001,3.980000,421.350006,130.440002,388.799988,84.099998,241.740005,27.910000